version: '3'
services:
  db:
    image: mysql:5.7
    container_name: sql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
    ports:
      - '3307:3307'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    image: chat_system_rails_image
    container_name: web_container
    ports:
      - '3000:3000'
    volumes: 
            - ".:/app"
    depends_on:
      - db
    command: >
      /bin/sh -c "
      rm -f /app/tmp/pids/server.pid && rails s -b '0.0.0.0'"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    ports:
      - '9200:9200'
      - '9300:9300'


volumes:
  mysql_data: