version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
    ports:
      - '3307:3307'
    volumes:
      - mysql_data:/var/lib/mysql


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    ports:
      - '9200:9200'
      - '9300:9300'
    
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  sidekiq:
    build:
      context: .
    container_name: sidekiq_container
    command: bundle exec sidekiq --verbose
    links:
      - db
      - redis
  web:
    build: .
    image: chat_system_rails_image
    container_name: web_container
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes: 
            - ".:/app"
    depends_on:
      - db
      - redis
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && rake db:migrate && rails s -b '0.0.0.0'; bundle exec sidekiq"







volumes:
  mysql_data:
  redis: